# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 05:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_abbreviation', models.CharField(max_length=5)),
                ('office_city', models.CharField(max_length=200)),
                ('office_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(max_length=500)),
                ('reservation_title', models.CharField(max_length=200)),
                ('reservation_attendees', models.CharField(max_length=200)),
                ('reservation_start', models.DateTimeField(default=datetime.datetime(2016, 4, 25, 5, 37, 20, 78144, tzinfo=utc))),
                ('reservation_end', models.DateTimeField(default=datetime.datetime(2016, 4, 25, 5, 52, 20, 78219, tzinfo=utc))),
                ('reservation_owner', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name_short', models.CharField(max_length=200)),
                ('room_name_long', models.CharField(max_length=200)),
                ('room_mailbox', models.CharField(max_length=200)),
                ('room_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_calendar.OfficeLocation')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_calendar.Room'),
        ),
    ]
